# Generated by Django 4.2.16 on 2026-03-04 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("reporting", "0066_load_default_acronyms"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportAcronymExpansion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "acronym",
                    models.CharField(
                        db_index=True,
                        help_text="The acronym that was expanded (e.g., 'ACL')",
                        max_length=50,
                        verbose_name="Acronym",
                    ),
                ),
                (
                    "expansion",
                    models.TextField(
                        help_text="The full text expansion used (e.g., 'Access Control List')",
                        verbose_name="Expansion",
                    ),
                ),
                (
                    "expanded_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this acronym was first expanded in the report",
                        verbose_name="Expanded At",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        help_text="The report this expansion belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acronym_expansions",
                        to="reporting.report",
                    ),
                ),
            ],
            options={
                "verbose_name": "Report Acronym Expansion",
                "verbose_name_plural": "Report Acronym Expansions",
                "ordering": ["acronym"],
                "indexes": [
                    models.Index(
                        fields=["report", "acronym"],
                        name="reporting_r_report__994ab5_idx",
                    )
                ],
                "unique_together": {("report", "acronym")},
            },
        ),
    ]
